name: telegram message
on:
  workflow_dispatch:
  schedule:
    - cron: '*/10 * * * *'

jobs:
  check:
    name: check
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master

      - uses: actions/setup-node@v1

      - uses: microsoft/playwright-github-action@v1

      - name: Install dependencies
        run: npm install

      - name: Run Script
        id: run_script_check
        run: |
          LOCATIONS=$(node index.js)
          LOCATIONS="${LOCATIONS//'%'/'%25'}"
          LOCATIONS="${LOCATIONS//$'\n'/'%0A'}"
          LOCATIONS="${LOCATIONS//$'\r'/'%0D'}"
          echo "::set-output name=content::$LOCATIONS"
      - name: send custom message
        uses: appleboy/telegram-action@master
        with:
          to: ${{ secrets.TELEGRAM_TO }}
          token: ${{ secrets.TELEGRAM_TOKEN }}
          message: |
            ${{ steps.run_script_check.outputs.content }}